#!/usr/bin/perl

use strict;
use warnings;
use Data::Dump qw(dump);

my $input  = q(supz '"supz", awesome');
my @output = main->_process_space_delimited($input);

print "", dump(\@output), "\n";

sub _process_space_delimited {
    my $this = shift;

    return
        grep {defined} ($_[0] =~ m/["']([^"']*?)["']|(\S+)/g)
}   
